# Generated by Django 5.2 on 2025-05-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_post_description_alter_post_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='announcement',
            new_name='title',
        ),
    ]
